[queries]
dreamkg = ["Outpatient services"]
biobricks-tox21 = ["chemical containing chlorine"]
wildlifekn = ["tree frog"]
nde = ["influenza virus"]
biobricks-aopwiki = ["mammal"]
ruralkg = ["alcohol abuse"]
