apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frink-embedding-ui.fullname" . }}
  labels:
    {{- include "frink-embedding-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "frink-embedding-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "frink-embedding-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "QDRANT_HOST"
              value: {{ .Values.env.qdrantHost }}
            - name: "QDRANT_PORT"
              value: {{ .Values.env.qdrantPort | quote }}
            - name: "QDRANT_COLLECTION"
              value: {{ .Values.env.qdrantCollection }}
            - name: "SENTENCE_MODEL_NAME"
              value: {{ .Values.env.model }}
            - name: "SENTENCE_TRANSFORMERS_HOME"
              value: {{ .Values.env.sentenceTransformersHome }}
            - name: SCRIPT_NAME
              value: {{ .Values.env.webPath }}
          command:
            - .venv/bin/gunicorn
          args:
            - -b
            - 0.0.0.0:5000
            - src.frink_embeddings_web:app
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: {{.Values.env.webPath }}*/}}
{{/*              port: http*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: {{.Values.env.webPath }}*/}}
{{/*              port: http*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.env.sentenceTransformersHome }}
              name: models-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: models-pvc
          persistentVolumeClaim:
            claimName: {{ include "frink-embedding-ui.fullname" . }}-models-pvc
