{{ if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "frink-embedding-ui.fullname" . }}
spec:
  parentRefs:
    {{ range .Values.gateway.parentRefs  }}
    - name: {{ .name }}
      namespace: {{ .namespace }}
    {{  end }}
  hostnames:
  - {{ .Values.gateway.host }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.gateway.path }}
    backendRefs:
    - name: {{ include "frink-embedding-ui.fullname" . }}
      port: {{ .Values.service.port }}
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "frink-embedding-ui.fullname" . }}
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    config:
      type: HTTP
      httpHealthCheck:
        port: 5000
        requestPath: "{{ .Values.gateway.path }}/"
  targetRef:
    group: ""
    kind: Service
    name: {{ include "frink-embedding-ui.fullname" . }}
{{ end }}